### ISSUE TITLE
Ubuntu 17.10 - extension errors

### ISSUE THREAD

**Issue by tk421storm** [zpydr/gnome-shell-extension-taskbar#176] opened 2018-01-24 16:30 UTC
I'm having trouble re-enabling this extension after upgrading to 17.10. It seems like Ubuntu may have screwed something up, as I've seen other extension bug reports for this version. here's my gnome-shell log:

Jan 24 11:21:08 oppenheimer gnome-shell[1682]: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-wsSBEjhCIB: Connection refused
Jan 24 11:21:15 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
Jan 24 11:21:15 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
Jan 24 11:21:15 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
Jan 24 11:21:16 oppenheimer org.gnome.Shell.desktop[1682]: current session already has an ibus-daemon.
Jan 24 11:21:16 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Jan 24 11:21:16 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
Jan 24 11:21:17 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: "XF86RFKill" is not a valid accelerator
Jan 24 11:21:17 oppenheimer gnome-shell[1682]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Jan 24 11:21:18 oppenheimer gnome-shell[1682]: GNOME Shell started at Wed Jan 24 2018 11:21:16 GMT-0500 (EST)
Jan 24 11:21:46 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/modalDialog.js 218]: reference to undefined property "GdkX11Screen"
Jan 24 11:21:47 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Jan 24 11:21:47 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
Jan 24 11:21:47 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
Jan 24 11:21:47 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
Jan 24 11:21:48 oppenheimer org.gnome.Shell.desktop[1682]: current session already has an ibus-daemon.
Jan 24 11:21:48 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Jan 24 11:21:48 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
Jan 24 11:21:48 oppenheimer gnome-shell[1682]: JS WARNING: [/usr/share/gnome-shell/extensions/TaskBar@zpydr/extension.js 1357]: reference to undefined property 0
Jan 24 11:21:48 oppenheimer gnome-shell[1682]: Extension "TaskBar@zpydr" had error: TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined
Jan 24 11:21:48 oppenheimer gnome-shell[1682]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Jan 24 11:21:49 oppenheimer gnome-shell[1682]: GNOME Shell started at Wed Jan 24 2018 11:21:48 GMT-0500 (EST)
Jan 24 11:21:49 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: "XF86RFKill" is not a valid accelerator
Jan 24 11:22:01 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:02 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:02 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:03 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:03 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:04 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:04 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:04 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:05 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:05 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:05 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400008 (Software)
Jan 24 11:22:50 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/modalDialog.js 218]: reference to undefined property "GdkX11Screen"
Jan 24 11:22:51 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Jan 24 11:22:51 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
Jan 24 11:22:51 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
Jan 24 11:22:51 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
Jan 24 11:22:52 oppenheimer org.gnome.Shell.desktop[1682]: current session already has an ibus-daemon.
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: Some code accessed the property 'Util' on the module 'main'. That property was defined with 'let' or 'const' inside the module. This was previously suppo
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: JS WARNING: [/usr/share/gnome-shell/extensions/TaskBar@zpydr/extension.js 1357]: reference to undefined property 0
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: Extension "TaskBar@zpydr" had error: TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined
Jan 24 11:22:52 oppenheimer gnome-shell[1682]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Jan 24 11:22:53 oppenheimer org.gnome.Shell.desktop[1682]: Window manager warning: "XF86RFKill" is not a valid accelerator
Jan 24 11:22:53 oppenheimer gnome-shell[1682]: GNOME Shell started at Wed Jan 24 2018 11:22:52 GMT-0500 (EST)
Jan 24 11:24:38 oppenheimer gnome-shell[1682]: polkitAuthenticationAgent: Received 2 identities that can be used for authentication. Only considering one.
Jan 24 11:24:41 oppenheimer gnome-shell[1682]: JS WARNING: [resource:///org/gnome/shell/ui/modalDialog.js 218]: reference to undefined property "GdkX11Screen"

**Comment by psiphi75** [comment] 2018-01-28 21:22
I get the same issue.  I am running Gnome 3.26.2 on Ubuntu 17.10.  It seems the issue is due to the error below.  

By default the Misc->"Hot Corner" setting is enabled, if you disable this setting the error below occurs.  And TaskBar fails to load.  Leaving this setting as default (enabled) fixes the loading issue.  It appears Gnome Tweak Tool has a similar issue, in that is has trouble changing this value.

```
Jan 29 10:06:00 hp gnome-shell[2464]: JS ERROR: TypeError: Main.layoutManager.hotCorners[Main.layoutManager.primaryIndex] is undefined
                                      TaskBar.prototype.initEnableHotCorner@/home/simon/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:1445:13
                                      TaskBar.prototype.enableHotCorner@/home/simon/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js:1434:9
```

**Comment by Taz8du29** [comment] 2018-02-23 19:57
It's because the option is now available in [gnome-tweaks since 3.26.1](https://gitlab.gnome.org/GNOME/gnome-tweaks/blob/master/NEWS#L133)

**Comment by Taz8du29** [comment] 2018-02-24 02:30
This is a working, but temporary fiw, until [this discussion](https://bugzilla.gnome.org/show_bug.cgi?id=688320) ends.

**Comment by zpydr** [comment] 2018-04-04 23:26
fixed with last commits

**Closed by zpydr** 2018-04-04 23:26 UTC
Labels: bug
